<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Saipavan" failures="3" tests="9" name="ParellelExecution" time="0.116" errors="0" timestamp="2020-07-03T03:55:59 IST">
  <testcase classname="com.testexecution.java.CalcParellel1" name="Add" time="0.003"/>
  <testcase classname="com.testexecution.java.CalcParellel1" name="Multiplication" time="0.002"/>
  <testcase classname="com.testexecution.java.CalcParellel1" name="Sub" time="0.003"/>
  <testcase classname="com.testexecution.java.CalcParellel1" name="div" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [21.0] but found [22.0]">
      <![CDATA[java.lang.AssertionError: expected [21.0] but found [22.0]
at com.testexecution.java.CalcParellel1.div(CalcParellel1.java:59)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- div -->
  <testcase classname="com.testexecution.java.CalcParellel2" name="Modulus" time="0.002">
    <failure type="java.lang.AssertionError" message="did not expect [3] but found [3]">
      <![CDATA[java.lang.AssertionError: did not expect [3] but found [3]
at com.testexecution.java.CalcParellel2.Modulus(CalcParellel2.java:32)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- Modulus -->
  <testcase classname="com.testexecution.java.CalcParellel2" name="Negate" time="0.005"/>
  <testcase classname="com.testexecution.java.CalcParellel2" name="Powerof" time="0.002"/>
  <testcase classname="com.testexecution.java.CalcParellel2" name="Powerof1" time="0.002"/>
  <testcase classname="com.testexecution.java.CalcParellel2" name="invert" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [0.5] but found [0.02]">
      <![CDATA[java.lang.AssertionError: expected [0.5] but found [0.02]
at com.testexecution.java.CalcParellel2.invert(CalcParellel2.java:20)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- invert -->
</testsuite> <!-- ParellelExecution -->
