<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Saipavan" failures="1" tests="4" name="com.testexecution.java.CalcParellel1" time="0.011" errors="0" timestamp="2020-07-03T03:55:59 IST" skipped="0">
  <testcase classname="com.testexecution.java.CalcParellel1" name="Multiplication" time="0.002"/>
  <system-out>
Multipication executed  20  </system-out>
  <testcase classname="com.testexecution.java.CalcParellel1" name="Sub" time="0.003"/>
  <system-out>
Substraction Function executed  1  </system-out>
  <testcase classname="com.testexecution.java.CalcParellel1" name="Add" time="0.003"/>
  <system-out>
AdditionFunction executed  80  </system-out>
  <testcase classname="com.testexecution.java.CalcParellel1" name="div" time="0.003">
    <failure message="expected [21.0] but found [22.0]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [21.0] but found [22.0]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:968)
at org.testng.Assert.assertEquals(Assert.java:640)
at org.testng.Assert.assertEquals(Assert.java:651)
at com.testexecution.java.CalcParellel1.div(CalcParellel1.java:59)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
]]>
    </failure>
  </testcase> <!-- div -->
  <system-out>
Division Function executed  22.0  </system-out>
</testsuite> <!-- com.testexecution.java.CalcParellel1 -->
